# Generated by Django 3.2.12 on 2026-01-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['name'], include=('created_at',), name='job_name_covering_idx'),
        ),
        migrations.AddIndex(
            model_name='jobstatus',
            index=models.Index(fields=['job', '-timestamp'], include=('status_type',), name='jobstatus_latest_covering_idx'),
        ),
    ]
